# Generated by Django 5.2 on 2025-04-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_options_review_img_review_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель авто'),
        ),
    ]
